dataset_path: nyu-visionx/VSI-SUPER-Recall
dataset_kwargs:
  token: True
  cache_dir: cambrians_vsr
  video: True
task: cambrians_vsr_10mins
test_split: test
output_type: generate_until
process_docs: !function utils.process_docs_10mins
doc_to_visual: !function utils.doc_to_visual
doc_to_text: !function utils.doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
# The return value of process_results will be used by metrics
process_results: !function utils.process_results
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
metric_list:
  - metric: score
    aggregation: !function utils.aggregate_results
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
  gemini_api:
    pre_prompt: ""
    post_prompt: ""
  gpt4v:
    pre_prompt: ""
    pre_prompt: ""
metadata:
  - version: 0.0
